dataroot: /data/giorgio/prost
bacdive_user: gonnella@zbh.uni-hamburg.de
bacdive_pass: bacdivepass
dbuser: prostuser
dbpass: prostpass
dbname: prostdb
testdbname: prosttestdb
dbrootpass: root
sysuser: gonnella
domains: [archaea, bacteria]
